
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ANSHPREET SINGH
 */
public class categories_home extends javax.swing.JFrame {

    /**
     * Creates new form user_home
     */
    public categories_home(String email) {
        initComponents();
        setSize(500,500);
        setLocationRelativeTo(null);
        ImageIcon ic = new ImageIcon("src/background.jpg");
        Image im = ic.getImage().getScaledInstance(background2.getWidth(),background2.getHeight(),Image.SCALE_SMOOTH);
        background2.setIcon(new ImageIcon(im));
        background2.setText("Welcome: "+email);
        loadcategory();
        mainpanel.setOpaque(true);
       
    }
    
    void loadcategory()
    {
        String ans = myClient.fetchcat();
        System.out.println(ans);
        StringTokenizer st = new StringTokenizer(ans,";;");
        int n = st.countTokens();
        JButton[] arr = new JButton[n];
        
        int x=15,y=100;
        for(int i=0;i<n;i++)
        {
            String row = st.nextToken();
            StringTokenizer st1 = new StringTokenizer(row,"$");
            String name = st1.nextToken();
            String photo = st1.nextToken();
            
            arr[i]= new JButton(name);
            arr[i].setIcon(new ImageIcon(photo));
            arr[i].setBounds(x,y,120, 40);
            arr[i].setFont(new java.awt.Font("Segoe UI", 1, 14));
            arr[i].addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                   fetch_movies obj = new fetch_movies(name);
                   obj.setVisible(true);
                }
            });
            mainpanel.add(arr[i]);
            mainpanel.repaint();
            
            if(x<=410)
            {
               x+=120; 
            }
            else
            {
                x=15;
                y+=50;
            }
                    
        }
        mainpanel.setPreferredSize(new Dimension(450,n*50));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mainpanel = new javax.swing.JPanel();
        background2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        background.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        background.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        background.setText("WELCOME");
        getContentPane().add(background);
        background.setBounds(0, 0, 500, 60);

        mainpanel.setBackground(new java.awt.Color(204, 255, 204));
        jScrollPane1.setViewportView(mainpanel);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 80, 460, 370);

        background2.setText("jLabel1");
        getContentPane().add(background2);
        background2.setBounds(-3, -4, 510, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(categories_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(categories_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(categories_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(categories_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new categories_home("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel background2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
