
import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;


public class Server_ON_OFF extends javax.swing.JFrame {

    myServer obj;
   
    public Server_ON_OFF() {
       
        initComponents();
        setSize(500, 520);
        setLocationRelativeTo(null);
        ImageIcon ic = new ImageIcon("src/server.jpg");
        Image im = ic.getImage().getScaledInstance(background.getWidth(),background.getHeight(),Image.SCALE_SMOOTH);
        background.setIcon(new ImageIcon(im)); 
        stopbt.setEnabled(false);
        jButton1.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startbt = new javax.swing.JButton();
        stopbt = new javax.swing.JButton();
        lb = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        startbt.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        startbt.setText("Start Server");
        startbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startbtActionPerformed(evt);
            }
        });
        getContentPane().add(startbt);
        startbt.setBounds(140, 110, 200, 80);

        stopbt.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        stopbt.setText("Stop Server");
        stopbt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopbtActionPerformed(evt);
            }
        });
        getContentPane().add(stopbt);
        stopbt.setBounds(140, 240, 200, 80);

        lb.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        lb.setForeground(new java.awt.Color(255, 51, 51));
        lb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb.setText("Server OFF !!!");
        getContentPane().add(lb);
        lb.setBounds(0, 0, 500, 70);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButton1.setText("Enter V.O.D.");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(12, 15, 12, 15, new javax.swing.ImageIcon(getClass().getResource("/background.jpg")))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 370, 240, 90);
        getContentPane().add(background);
        background.setBounds(-10, -10, 520, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startbtActionPerformed
        
        try {
            obj = new myServer(9000);
            startbt.setEnabled(false);
            lb.setText("Server ON ...");
            lb.setForeground(Color.green);
            stopbt.setEnabled(true);
            jButton1.setEnabled(true);
        } 
        catch (Exception e)
        {
            e.printStackTrace();
        }
        
        
    }//GEN-LAST:event_startbtActionPerformed

    private void stopbtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopbtActionPerformed
       obj.shutdown();
       startbt.setEnabled(true);
       lb.setText("Server OFF !!!");
       lb.setForeground(Color.RED);
       stopbt.setEnabled(false);
       jButton1.setEnabled(false);
    }//GEN-LAST:event_stopbtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Welcome obj1 = new Welcome();
        obj1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server_ON_OFF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server_ON_OFF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server_ON_OFF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server_ON_OFF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Server_ON_OFF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lb;
    private javax.swing.JButton startbt;
    private javax.swing.JButton stopbt;
    // End of variables declaration//GEN-END:variables
}
